### ISSUE TITLE
Any alternatives for showcasing audio clips' differences?

### ISSUE THREAD

**Issue by ThreeDeeJay** [audiolabs/trackswitch.js#11]
I've been looking for a website to upload/link audio clips to compare and notice differences by switching between them during playback, but without having to manually code/maintain HTML like trackswitch.js. So far, I've only found Vidyard, but it requires setting up a video file with multiple tracks [like this](https://share.vidyard.com/watch/RNK9HAzbAhD9funBsp6Emt), but I want something more flexible (that allows adding/removing/replacing audio clips) and intuitive (single click to switch between clips like trackswitch)

**Comment by nils-werner** [comment]
You can try https://share.unmix.app/

**Comment by ThreeDeeJay** [comment]
> You can try https://share.unmix.app/

@nils-werner This would be perfect, though I'm having some issues with it.
Mega and Google Drive links don't work and it strips dropbox links from the rlkey parameter (which apparently is required for public links now), which then breaks the preview (stuck loading) unless I manually paste it, so at least there's a workaround.
But once I set up the clips and I'm even able to play and cycle through them, clicking Share doesn't do anything (it doesn't update `https://share.unmix.app` or `https://share.unmix.app/embed` if checking embed, tested multiple browsers), so I don't get the link to actually give others to play the clips on their ends.
![image](https://i.imgur.com/KIpcZMX.gif)
Does it work on your end? Sadly the project seems abandoned and not even the [homepage demo](https://share.unmix.app/) works so I hope there are more alternatives 😔

**Comment by faroit** [comment]
@ThreeDeeJay the cloud storage is indeed not working anymore as I stopped paying for it ;)

The code works fine though and you can easily set this up yourself using just a Google firebase key.

**Comment by ThreeDeeJay** [comment]
@faroit Actually hold up, I just noticed the example on the homepage is working again, and so does sharing 👀👌 
https://share.unmix.app/CAKRMzcmYQNAUvAuRipJ

**Comment by faroit** [comment]
> @faroit Actually hold up, I just noticed the example on the homepage is working again, and so does sharing 👀👌 
> 
> https://share.unmix.app/CAKRMzcmYQNAUvAuRipJ

@ThreeDeeJay Yes, I just turned it on again. I would still recommend to fork the project and host it yourself

**Comment by ThreeDeeJay** [comment]
@faroit Fair enough, I might give it a shot, though to be honest I have almost no experience with self-hosting, especially if it requires setting up a home or cloud server/domain. 😅 
And when you mentioned cloud storage, is that for each share's URLs/details/etc., the website or both?
because I wonder if implementing an option to pass each clip/details via URL parameter would bypass the need for paying for storage 🤔 
Either way, this works perfectly for now, but for anyone else stumbling upon this thread, feel free to suggest alternatives worth checking out.

**Comment by ThreeDeeJay** [comment]
> @ThreeDeeJay The database is for storing the colors and other metadata. I think it might be possible to encode all in the url but it would be limited to 5 stems or so.

@faroit How about piggy-backing on something like PasteBin by reusing its URL ID to fetch the metadata as plain-text?
So https://pastebin.com/raw/Nuf4H0MV would become something like https://share.unmix.app/pastebin/Nuf4H0MV
I think that'd also allow being able to edit the metadata if the PasteBin was created using an account. They have an [API available](https://pastebin.com/doc_api) but hopefully this works without requiring people to get their own API key, so kinda like how Unmix can just fetch Dropbox files. 🤔
