### ISSUE TITLE
trackswitch does not support Chrome 70

### ISSUE THREAD

**Issue by faroit** [audiolabs/trackswitch.js#2]
Chrome 66 was released a few days ago and trackswitch falls to the victim from the recent changes of Chromes new user interaction model:

```
The AudioContext was not allowed to start. It must be resume (or created) 
after a user gesture on the page. https://goo.gl/7K7WLu
```

That means trackswitch doesn't play audio on Chrome 66 at all, so this would need to be addressed asap.

**Comment by faroit** [comment]
I don't know what exactly has changed in Chrome but it works fine now in 66.0.3359.139

Maybe someone else can try it on Linux/Windows?

**Comment by faroit** [comment]
not working at all in Version 66.0.3359.170. @nils-werner @stefan-balke can you confirm this?

**Comment by stefan-balke** [comment]
Yes, I can confirm that.

**Comment by stefan-balke** [comment]
Have you tried exchanging

https://github.com/audiolabs/trackswitch.js/blob/master/js/trackswitch.js#L637

with `.resume()`?

**Comment by sebastianrosenzweig** [comment]
Still works for me on Chrome 66.0.3359.170 and macOS High Sierra.

**Comment by stefan-balke** [comment]
Please completely shut down the browser (cmd + Q) and try again.

**Comment by sebastianrosenzweig** [comment]
Now I tried another site and it does not work. So it seems to be configuration dependent...

**Comment by stefan-balke** [comment]
I have a solution, will make a PR.

**Comment by faroit** [comment]
> Note: The Web Audio API will be included in the Chrome autoplay policy with M70 (October 2018).

this will break trackswitch again.

**Comment by stefan-balke** [comment]
Okay, gonna finish #3 then soonish.

**Comment by faroit** [comment]
@stefan-balke seems like Google is scared:

> The Web Audio API will be included in the Chrome autoplay policy with M71 (December 2018).

so lets fix this before christmas

**Comment by faroit** [comment]
trackswitch now stopped working on chrome. I would propose to add a warning in the readme until this is fixed

**Comment by stefan-balke** [comment]
Still running or again. Can't recall the details though.
