### ISSUE TITLE
Add dist folder to release zip

### ISSUE THREAD

**Issue by faroit** [audiolabs/trackswitch.js#5]
the readme states that the dist folder is `included`. But then it refers to the `gh-pages` branch or the npm upload, where this is the case. 

It would be more convenient for non npm users to just offer a link to the github release zip which includes this folder and its minified libs.

**Comment by nils-werner** [comment]
You can download the `gh-branch` as a ZIP using this URL: https://github.com/audiolabs/trackswitch.js/archive/gh-pages.zip

Should we link to it/mention it somewhere?

**Comment by nils-werner** [comment]
I have added a link to the ZIP on https://audiolabs.github.io/trackswitch.js/

**Comment by faroit** [comment]
I would have prefered just the zipped dist folder. But this is already helpful for beginners. Thanks!
